### ISSUE TITLE
Google Sheets, Private Key

### ISSUE THREAD

**Issue by ChrisAntaki** [madeofpeople/delegatescampaign#1]
Great job on the website. I just noticed a private key embedded in a JSON file. Security issue?
https://github.com/madeofpeople/delegatescampaign/blob/master/metalsmith.json#L9

**Comment by ChrisAntaki** [comment]
Be safe. :smile:

**Comment by thiagodemellobueno** [comment]
You are correct, and thanks. This project had a short lifespan and is effectively dormant.
But indeed you are correct this was a horrible practice!
